### ISSUE TITLE
GAMES - Badge ordering

### ISSUE THREAD

**Issue by caroisatotaln00b** [tonifisler/epicgamejam#22]
Au risque de passer pour quelqu'un qui aime l'ordre avec furreur, je préfèrerais que les badges se déroulent sous mes yeux de manière alphabétique. Mais je peux me plier à vos volontés...
SEULEMENT si vous ne me mettez pas le 25 subthemes entre le 5 et le 15 ! Ca me demande biiiiien trop d'effort pour apprécier l'epicness du tout.

**Comment by tonifisler** [comment]
Done.
