### ISSUE TITLE
@NIFFF - New this year...

### ISSUE THREAD

**Issue by caroisatotaln00b** [tonifisler/epicgamejam#25]
So, if you can't make it TO Neuchâtel.

Et vu que c'est quand même tellement la classe qu'on y croit pas, je pense que ça vaut la peine d'insister sur le gratuit. Donc:

Costs: Free. Yeah, you read that right: FREE!

ou alors... mettre FREE en majuscules dans la bouffe et les boissons. Up to you!

**Comment by tonifisler** [comment]
Done.
